const Hotels = [{
    id: 1,
    image: require("../assets/hotels/a2b.jpg"),
    name: 'Adayar Anandha Bhavan',
    time: '32min',
    rate: '₹₹',
    area: 'Ashok Nagar',
},
{
    id: 2,
    image: require("../assets/hotels/annarosi.jpeg"),
    name: 'Anna Rosi',
    time: '28min',
    rate: '₹₹₹',
    area: 'Anna Nagar',
},
{
    id: 3,
    image: require("../assets/hotels/buhari.jpeg"),
    name: 'Buhari',
    time: '30min',
    rate: '₹₹',
    area: 'Nandhanam',
},
{
    id: 4,
    image: require("../assets/hotels/burgerking.jpeg"),
    name: 'Burger King',
    time: '22min',
    rate: '₹₹₹',
    area: 'Velacheri',
},
{
    id: 5,
    image: require("../assets/hotels/mcd.jpeg"),
    name: 'Mc Donalds',
    time: '12min',
    rate: '₹',
    area: 'Ashok Pillar',
},
{
    id: 6,
    image: require("../assets/hotels/saravana.jpeg"),
    name: 'Saravana Bhavan',
    time: '27min',
    rate: '₹₹',
    area: 'Ekatuthangal',
},
{
    id: 7,
    image: require("../assets/hotels/shakeshak.jpeg"),
    name: 'Shake Shack',
    time: '25min',
    rate: '₹',
    area: 'Vepperi',
},
{
    id: 8,
    image: require("../assets/hotels/vangoo.jpeg"),
    name: 'Italic Cafe',
    time: '35min',
    rate: '₹',
    area: 'Vepperi',
},
{
    id: 9,
    image: require("../assets/hotels/vasanth.jpeg"),
    name: 'Vasantha Bhavan',
    time: '28min',
    rate: '₹₹',
    area: 'Vepperi',
},
{
    id: 10,
    image: require("../assets/hotels/wendys.jpeg"),
    name: 'Wendys',
    time: '20min',
    rate: '₹',
    area: 'Vepperi',
},
{
    id: 11,
    image: require("../assets/hotels/Anjappa.jpeg"),
    name: 'Anjappar',
    time: '42min',
    rate: '₹₹',
    area: 'Madipakkam',
},
{
    id: 12,
    image: require("../assets/hotels/Bilal.jpeg"),
    name: 'Bilal',
    time: '26min',
    rate: '₹₹₹',
    area: 'Mylapore',
},
{
    id: 13,
    image: require("../assets/hotels/Chick.jpeg"),
    name: 'Anna Nagar',
    time: '25min',
    rate: '₹₹',
    area: 'Nandhanam',
},
{
    id: 14,
    image: require("../assets/hotels/Chillis.jpeg"),
    name: 'Chillis',
    time: '22min',
    rate: '₹₹₹',
    area: 'Velacheri',
},
{
    id: 15,
    image: require("../assets/hotels/Chipotle.jpeg"),
    name: 'Chippotle',
    time: '12min',
    rate: '₹',
    area: 'Ashok Pillar',
},
{
    id: 16,
    image: require("../assets/hotels/Dunkin'donuts.jpeg"),
    name: "Dunkin' Donuts",
    time: '27min',
    rate: '₹₹',
    area: 'Ekatuthangal',
},
{
    id: 17,
    image: require("../assets/hotels/Lower.jpeg"),
    name: 'Lower Deck',
    time: '25min',
    rate: '₹₹₹',
    area: 'Porur',
},
{
    id: 18,
    image: require("../assets/hotels/Olive.jpeg"),
    name: 'Olive Garden',
    time: '35min',
    rate: '₹',
    area: 'Mambalam',
},
{
    id: 19,
    image: require("../assets/hotels/Popeyes.jpeg"),
    name: 'Popeyes',
    time: '28min',
    rate: '₹₹',
    area: 'Vepperi',
},
{
    id: 20,
    image: require("../assets/hotels/Tacobell.jpeg"),
    name: 'Taco Bell',
    time: '20min',
    rate: '₹',
    area: 'Perungudi',
},]
export default Hotels

