const Top = [{
    id: 1,
    image: require("../assets/hotels/a2b.jpg"),
    name: 'Adayar Anandha Bhavan',
    time: '32min',
    rate: '₹₹',
    area: 'Ashok Nagar',
},
{
    id: 2,
    image: require("../assets/hotels/annarosi.jpeg"),
    name: 'Anna Rosi',
    time: '28min',
    rate: '₹₹₹',
    area: 'Anna Nagar',
},
{
    id: 3,
    image: require("../assets/hotels/buhari.jpeg"),
    name: 'Buhari',
    time: '30min',
    rate: '₹₹',
    area: 'Nandhanam',
},
{
    id: 4,
    image: require("../assets/hotels/burgerking.jpeg"),
    name: 'Burger King',
    time: '22min',
    rate: '₹₹₹',
    area: 'Velacheri',
},
{
    id: 5,
    image: require("../assets/hotels/mcd.jpeg"),
    name: 'Mc Donalds',
    time: '12min',
    rate: '₹',
    area: 'Ashok Pillar',
},
{
    id: 6,
    image: require("../assets/hotels/saravana.jpeg"),
    name: 'Saravana Bhavan',
    time: '27min',
    rate: '₹₹',
    area: 'Ekatuthangal',
}]
export default Top